### ISSUE TITLE
MC agent missing code

### ISSUE THREAD

**Issue by jmsalash** [iocchi/RLgames#1]
When using MC I'm getting an error; a variable and a function are missing:
self.error = False
def set_action_names(self, an):
        self.action_names = an

For completeness, the function decision can be replicated from RLAgent to use the new function action_names

**Comment by iocchi** [comment]
Partially fixed. Please notice that the RLMCAgent is not aligned with other code: RLAgent with proper parameter nstep should be used instead of this.
